package awin

type DataFeedEntry struct {
	AwDeepLink                    string `json:"aw_deep_link,omitempty"`
	ProductName                   string `json:"product_name,omitempty"`
	AwProductId                   string `json:"aw_product_id,omitempty"`
	MerchantProductId             string `json:"merchant_product_id,omitempty"`
	MerchantImageUrl              string `json:"merchant_image_url,omitempty"`
	Description                   string `json:"description,omitempty"`
	MerchantCategory              string `json:"merchant_category,omitempty"`
	SearchPrice                   string `json:"search_price,omitempty"`
	MerchantName                  string `json:"merchant_name,omitempty"`
	MerchantId                    string `json:"merchant_id,omitempty"`
	CategoryName                  string `json:"category_name,omitempty"`
	CategoryId                    string `json:"category_id,omitempty"`
	AwImageUrl                    string `json:"aw_image_url,omitempty"`
	Currency                      string `json:"currency,omitempty"`
	StorePrice                    string `json:"store_price,omitempty"`
	DeliveryCost                  string `json:"delivery_cost,omitempty"`
	MerchantDeepLink              string `json:"merchant_deep_link,omitempty"`
	Language                      string `json:"language,omitempty"`
	LastUpdated                   string `json:"last_updated,omitempty"`
	DisplayPrice                  string `json:"display_price,omitempty"`
	DataFeedId                    string `json:"data_feed_id,omitempty"`
	BrandName                     string `json:"brand_name,omitempty"`
	BrandId                       string `json:"brand_id,omitempty"`
	Colour                        string `json:"colour,omitempty"`
	ProductShortDescription       string `json:"product_short_description,omitempty"`
	Specifications                string `json:"specifications,omitempty"`
	Condition                     string `json:"condition,omitempty"`
	ProductModel                  string `json:"product_model,omitempty"`
	ModelNumber                   string `json:"model_number,omitempty"`
	Dimensions                    string `json:"dimensions,omitempty"`
	Keywords                      string `json:"keywords,omitempty"`
	PromotionalText               string `json:"promotional_text,omitempty"`
	ProductType                   string `json:"product_type,omitempty"`
	CommissionGroup               string `json:"commission_group,omitempty"`
	MerchantProductCategoryPath   string `json:"merchant_product_category_path,omitempty"`
	MerchantProductSecondCategory string `json:"merchant_product_second_category,omitempty"`
	MerchantProductThirdCategory  string `json:"merchant_product_third_category,omitempty"`
	RrpPrice                      string `json:"rrp_price,omitempty"`
	Saving                        string `json:"saving,omitempty"`
	SavingsPercent                string `json:"savings_percent,omitempty"`
	BasePrice                     string `json:"base_price,omitempty"`
	BasePriceAmount               string `json:"base_price_amount,omitempty"`
	BasePriceText                 string `json:"base_price_text,omitempty"`
	ProductPriceOld               string `json:"product_price_old,omitempty"`
	DeliveryRestrictions          string `json:"delivery_restrictions,omitempty"`
	DeliveryWeight                string `json:"delivery_weight,omitempty"`
	Warranty                      string `json:"warranty,omitempty"`
	TermsOfContract               string `json:"terms_of_contract,omitempty"`
	DeliveryTime                  string `json:"delivery_time,omitempty"`
	InStock                       string `json:"in_stock,omitempty"`
	StockQuantity                 string `json:"stock_quantity,omitempty"`
	ValidFrom                     string `json:"valid_from,omitempty"`
	ValidTo                       string `json:"valid_to,omitempty"`
	IsForSale                     string `json:"is_for_sale,omitempty"`
	WebOffer                      string `json:"web_offer,omitempty"`
	PreOrder                      string `json:"pre_order,omitempty"`
	StockStatus                   string `json:"stock_status,omitempty"`
	SizeStockStatus               string `json:"size_stock_status,omitempty"`
	SizeStockAmount               string `json:"size_stock_amount,omitempty"`
	MerchantThumbUrl              string `json:"merchant_thumb_url,omitempty"`
	LargeImage                    string `json:"large_image,omitempty"`
	AlternateImage                string `json:"alternate_image,omitempty"`
	AwThumbUrl                    string `json:"aw_thumb_url,omitempty"`
	AlternateImageTwo             string `json:"alternate_image_two,omitempty"`
	AlternateImageThree           string `json:"alternate_image_three,omitempty"`
	AlternateImageFour            string `json:"alternate_image_four,omitempty"`
	Reviews                       string `json:"reviews,omitempty"`
	AverageRating                 string `json:"average_rating,omitempty"`
	Rating                        string `json:"rating,omitempty"`
	NumberAvailable               string `json:"number_available,omitempty"`
	Custom1                       string `json:"custom_1,omitempty"`
	Custom2                       string `json:"custom_2,omitempty"`
	Custom3                       string `json:"custom_3,omitempty"`
	Custom4                       string `json:"custom_4,omitempty"`
	Custom5                       string `json:"custom_5,omitempty"`
	Custom6                       string `json:"custom_6,omitempty"`
	Custom7                       string `json:"custom_7,omitempty"`
	Custom8                       string `json:"custom_8,omitempty"`
	Custom9                       string `json:"custom_9,omitempty"`
	Ean                           string `json:"ean,omitempty"`
	Isbn                          string `json:"isbn,omitempty"`
	Upc                           string `json:"upc,omitempty"`
	Mpn                           string `json:"mpn,omitempty"`
	ParentProductId               string `json:"parent_product_id,omitempty"`
	ProductGtin                   string `json:"product_gtin,omitempty"`
	BasketLink                    string `json:"basket_link,omitempty"`
}
